apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
spec:
  selector:
    matchLabels:
      app: kitchen
  replicas: 1
  template:
    metadata:
      labels:
        app: kitchen
    spec:
        containers:
        - image: kitchen
          imagePullPolicy: Never 
          name: kitchen
          ports:
          - containerPort: 8080
