apiVersion: apps/v1
kind: Deployment
metadata:
  name: beverages
spec:
  selector:
    matchLabels:
      app: beverages
  replicas: 1
  template:
    metadata:
      labels:
        app: beverages
    spec:
        containers:
        - image: chiniczr/beverages
          name: beverages
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: beverages
spec:
  type: NodePort
  selector:
    app: beverages
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

