apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  selector:
    matchLabels:
      app: checkout
  replicas: 1
  template:
    metadata:
      labels:
        app: checkout
    spec:
        containers:
        - image: chiniczr/checkout
          name: checkout
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  type: NodePort
  selector:
    app: checkout
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

