apiVersion: apps/v1
kind: Deployment
metadata:
  name: robots
spec:
  selector:
    matchLabels:
      app: robots
  template:
    metadata:
      labels:
        app: robots
    spec:
      containers:
      - name: robots
        image: chiniczr/robots
