apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  selector:
    matchLabels:
      app: websocket
  replicas: 1
  template:
    metadata:
      labels:
        app: websocket
    spec:
        containers:
        - image: chiniczr/websocket
          name: websocket
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: websocket
spec:
  type: NodePort
  selector:
    app: websocket
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

