apiVersion: apps/v1
kind: Deployment
metadata:
  name: calzones
spec:
  selector:
    matchLabels:
      app: calzones
  replicas: 1
  template:
    metadata:
      labels:
        app: calzones
    spec:
        containers:
        - image: calzones
          imagePullPolicy: Never 
          name: calzones
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calzones
spec:
  type: NodePort
  selector:
    app: calzones
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

